### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ChitownWillie** [AngelGryph/MadeInHeaven_ItemPack#1]
ERROR Installing [Made in Heaven: Item Pack], rolling back to previous state
Will uninstall 3158 files for [MIH_IP/SETUP-MIH_IP.TP2] component 0.
Uninstalled    3158 files for [MIH_IP/SETUP-MIH_IP.TP2] component 0.
ERROR: Failure("resource [otyugh.CRE] not found for 'COPY'")
Please make a backup of the file: SETUP-MIH_IP.DEBUG and look for support at: https://www.gibberlings3.net/forums/topic/
29992-my-new-made-in-heaven-mods/

BG:EE 2.6.
[SETUP-MIH_IP.DEBUG.LOG](https://github.com/AngelGryph/MadeInHeaven_ItemPack/files/7261064/SETUP-MIH_IP.DEBUG.LOG)
6

**Comment by AngelGryph** [comment]
Fixed in current master.
