### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by JoePagano** [AngelGryph/MadeInHeaven_ItemPack#2]
I'm getting some missing inventory icons for the mod-added items - hard to tell, but it might be specific to iwd items. Definitely observed with 

mh#iwd08 Black Swan Armor +2			Arnolinus the dwarf (shop)
mh#iwd09 Philter of Purification		(various temples)
mh#iwd10 Shield Ring				Planar Sphere (event)

Do those image/icon resources need to be installed somewhere? I'm using BG2 2.5EE, no BG 1/SoD/IWD install.

**Comment by AngelGryph** [comment]
Checked, icon files install normally in current master and Shield Ring does have an icon in my game.
